### ISSUE TITLE
Suggestion) why don`t we make fibo.py

### ISSUE THREAD

**Issue by HyeJin1221** [HyeJin1221/branch-practice#1]
-  Fibonacci Sequence를 구하는 파이썬 스크립트를 만들고 싶어요.

**Tasks**

- [ ] fibo with Recursion 
- [ ] fibo with Memoization
- [ ] fibo with Binet`s formula

$$F_n=\dfrac{\left(\dfrac{1+\sqrt{5}}{2}\right)^n-\left(\dfrac{1-\sqrt{5}}{2}\right)^n}{\sqrt{5}}$$
